### ISSUE TITLE
Rename `landusequery.txt` to `landusequery.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [peterjamesward/GPXmagicV3#11]
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*

I propose to rename all Overpass QL files in this repo to `*.overpassql` for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by peterjamesward** [comment]
Land use query is constructed at runtime, not retrieved from file.

**Comment by FloEdelmann** [comment]
But there is a file in the `notes` directory: https://github.com/peterjamesward/GPXmagicV3/blob/master/notes/landusequery.txt

I agree it's not just a query file but mainly notes, but it would eventually benefit from syntax highlighting, too. You could rename it to `*.overpassql` and wrap the non-OverpassQL parts in a comment `/* … */`.

**Comment by peterjamesward** [comment]
Fair point. Thanks. 

Peter

**Comment by peterjamesward** [comment]
Done.

**Comment by peterjamesward** [comment]
Done.

**Comment by FloEdelmann** [comment]
Thanks! :)
